In [1]:
import numpy as np
import pandas as pd
import tqdm as tqdm

DATASET = pd.read_parquet("hf://datasets/data-is-better-together/fineweb-c/dan_Latn/train-00000-of-00001.parquet")

In [4]:
pd.read_csv("annotations.csv")

,id,text,label
0,951,Fitness World Kildeskovshallen\nLidt væk fra d...,['None']
1,319,F책 kroppen tilbage i kommunikationen\ncosmogra...,['None']
2,904,"Mand til decorum kan vi daterer, men kun psyko...",['None']
3,157,gay erotiske historier gratis outcall massage ...,"['None', 'Minimal']"
4,388,Abercrombie & Fitch white Abercrombie & Fitch ...,['None']
...,...,...,...
62,455,Reference historie\nProduktions Direktør Peter...,['Excellent']
63,462,Taking it back to the 1990s the Aspio is inspi...,['Minimal']
64,118,- Denne begivenhed er allerede afholdt.\nDDEX2...,['Basic']
65,745,"FAB HOUSE HISTORIC CENTER GARDEN AND POOL\n4,8...",['Good']
66,313,"Jeg fik min søn, som læser til IT-supporter, o...",['Basic']