In [6]:
import numpy as np
import pandas as pd
import tqdm as tqdm

In [4]:
pd.read_csv("annotations.csv")

,id,text,label
0,951,Fitness World Kildeskovshallen\nLidt væk fra d...,['None']
1,319,F책 kroppen tilbage i kommunikationen\ncosmogra...,['None']
2,904,"Mand til decorum kan vi daterer, men kun psyko...",['None']
3,157,gay erotiske historier gratis outcall massage ...,"['None', 'Minimal']"
4,388,Abercrombie & Fitch white Abercrombie & Fitch ...,['None']
...,...,...,...
62,455,Reference historie\nProduktions Direktør Peter...,['Excellent']
63,462,Taking it back to the 1990s the Aspio is inspi...,['Minimal']
64,118,- Denne begivenhed er allerede afholdt.\nDDEX2...,['Basic']
65,745,"FAB HOUSE HISTORIC CENTER GARDEN AND POOL\n4,8...",['Good']
66,313,"Jeg fik min søn, som læser til IT-supporter, o...",['Basic']

In [5]:
DATASET = pd.read_parquet("hf://datasets/data-is-better-together/fineweb-c/dan_Latn/train-00000-of-00001.parquet")

In [8]:
DATASET

,id,text,educational_value_labels,annotator_ids,problematic_content_label_present,problematic_content_label_agreement,language_names,language_code
0,c293383d-cffc-4244-9e75-1cf1a25eb0cc,"Er du en af de mange, der ikke kan se 6′eren d...","[None, None, None]","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...",False,1.000000,dan_Latn,dan_Latn
1,8ebfa2e5-fdb4-494a-817a-3a5b0fe09475,Behandlingsområder\nHer kan du læse om regione...,"[None, Minimal]","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...",False,1.000000,dan_Latn,dan_Latn
2,917f3945-cec8-4cfe-8516-c72351489fa6,Schul Landskabsarkitekter arbejder med have- o...,"[None, Minimal, None]","[95e4f810-6fe7-4bbd-8be6-a11b0d069c11, a0585a5...",False,1.000000,dan_Latn,dan_Latn
3,8defb5be-a075-4709-9d61-db3632f61e13,Nyuddannede hurtigt i arbejde ad mælkevejen - ...,"[Minimal, Minimal]","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...",False,1.000000,dan_Latn,dan_Latn
4,f71ad46e-cd61-45fb-8ab7-d82bdd5885f1,I onsdags var Kristian og jeg inde og kigge på...,"[None, ❗ Problematic Content ❗, None]","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 9987848...",True,0.333333,dan_Latn,dan_Latn
...,...,...,...,...,...,...,...,...
995,da2d09ad-af5d-4690-8474-72152a61d4f8,Sorte singler datingYozshudal\nFind kærlighede...,"[❗ Problematic Content ❗, ❗ Problematic Conten...","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...",True,1.000000,dan_Latn,dan_Latn
996,74f77a6f-f30e-48d1-b90a-f1673bd2787a,"Datjng er mange gode grunde til, at kvinder, a...","[❗ Problematic Content ❗, None, ❗ Problematic ...","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, b98b014...",True,0.666667,dan_Latn,dan_Latn
997,cd146702-e112-415a-9017-83ebaed7390a,gay aroma thai massage århus porno ældre herre...,"[❗ Problematic Content ❗, ❗ Problematic Conten...","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, b98b014...",True,1.000000,dan_Latn,dan_Latn
998,a7d17d2b-90ec-4bc5-b6a7-ceb66c5d76e2,Borgerservice genåbner i dag\nBorgerservice i ...,"[Minimal, Minimal]","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...",False,1.000000,dan_Latn,dan_Latn
999,4ca17bc0-6e0e-47d2-b47c-fd28462b144f,|Titel :||Oathmark: Bring and Battle|\n|Regels...,"[Minimal, Minimal]","[a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...",False,1.000000,dan_Latn,dan_Latn