In [4]:
import pandas as pd
import numpy as np
import ast

In [ ]:
# df = pd.read_parquet("hf://datasets/data-is-better-together/fineweb-c/dan_Latn/train-00000-of-00001.parquet")
df = pd.read_csv("fineweb-c_relabled.csv")
df["educational_value_labels"] = df["educational_value_labels"].apply(ast.literal_eval)
# REMOVE PROBLEMATIC LABELS FROM DATASET
# df = df[df['problematic_content_label_present'] == False]

In [6]:
an1 = pd.read_csv("annotations/annotations.csv")
an2 = pd.read_csv("annotations/annotations-2.csv")
an3 = pd.read_csv("annotations/annotations-3.csv")

an1['label'] = an1['label'].apply(ast.literal_eval)
an2['label'] = an2['label'].apply(ast.literal_eval)
an3['label'] = an3['label'].apply(ast.literal_eval)

In [7]:
annotated_combined = pd.DataFrame()

# For each row in all an's:
for i in range(len(an1)):
    # Merge all labels into one df:
    an_anotatins = [an1.iloc[i]['label'][0], an2.iloc[i]['label'][0], an3.iloc[i]['label'][0]]
    fbc_annotations = ast.literal_eval(df[df["Unnamed: 0"] == int(an1.iloc[i]["id"])]["educational_value_labels"].values[0])
    for j in fbc_annotations:
        an_anotatins.append(j)

    combined_row = pd.DataFrame({
        'id': an1.iloc[i]['id'],
        'label': [an_anotatins]
    })
    annotated_combined = pd.concat([annotated_combined, combined_row], ignore_index=False)

annotated_combined.rename(columns={'label': 'education_value_labels'}, inplace=True)
annotated_combined.sample(5)

    id                             education_value_labels
0  284                  [None, None, None, None, Minimal]
0  710           [Basic, None, None, None, Minimal, None]
0  400  [Problematic, Problematic, Problematic, ❗ Prob...
0  313         [Minimal, None, Minimal, Minimal, Minimal]
0  558         [Minimal, Minimal, None, Minimal, Minimal]

In [49]:
sort_order = {
    "None": 0,
    "Minimal": 1,
    "Basic": 2,
    "Good": 3,
    "Excellent": 4
}

def encoding(edu_list):
    labels = set(edu_list)
    L = [0 for _ in range(len(sort_order))]
    for label in labels:
        if label in sort_order:
            L[sort_order[label]] = 1
    return L

def disagreement(encoding):
    indices = [i for i, val in enumerate(encoding) if val == 1]
    print(len(indices), indices)
    if len(indices) > 2:
        return True
    
    if len(indices) == 2:
        dist = abs(indices[0] - indices[1])
        print(dist)
        if dist > 1:
            return True
    
    return False


df["encoding"] = df["educational_value_labels"].apply(encoding)
df["disagreement"] = df["encoding"].apply(disagreement)

hd_df = df[df["disagreement"] == True]

0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []
0 []

In [9]:
annotated_combined['encoding'] = annotated_combined['education_value_labels'].apply(encoding)
annotated_combined['disagreement'] = annotated_combined['encoding'].apply(disagreement)
hd_annotated_combined = annotated_combined[annotated_combined["disagreement"] == True]

3 [0, 1, 3]
2 [0, 1]
1
2 [0, 1]
1
1 [0]
3 [0, 1, 2]
3 [0, 1, 2]
3 [2, 3, 4]
1 [0]
1 [1]
2 [0, 1]
1
2 [1, 2]
1
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
0 []
2 [0, 1]
1
2 [1, 2]
1
2 [0, 1]
1
1 [0]
2 [0, 2]
2
3 [0, 1, 4]
2 [0, 1]
1
3 [1, 2, 3]
1 [0]
2 [0, 1]
1
2 [0, 1]
1
3 [0, 1, 2]
1 [0]
2 [0, 1]
1
2 [0, 1]
1
1 [0]
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
1 [0]
5 [0, 1, 2, 3, 4]
3 [0, 1, 2]
0 []
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
3 [0, 1, 2]
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
2 [0, 1]
1
1 [0]
0 []

In [51]:
len(hd_df), len(hd_annotated_combined) # 0: No disagreement

(0, 11)

In [4]:
t = df.iloc[170]["encoding"]
display(t)
disagreement(t)

[1, 0, 0, 0, 0]

1 [0]

False

In [5]:
df.iloc[718]

id                                                  3e62b61f-c3d3-4244-9535-bc813a48e6a3
text                                   Musik- og sangtalenterne i Haderslev styrkes\n...
educational_value_labels                                                 [None, Minimal]
annotator_ids                          [a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f, 85ac8d5...
problematic_content_label_present                                                  False
problematic_content_label_agreement                                                  1.0
language_names                                                                  dan_Latn
language_code                                                                   dan_Latn
encoding                                                                 [1, 1, 0, 0, 0]
disagreement                                                                       False
Name: 884, dtype: object

In [11]:
hd_annotated_combined

,id,education_value_labels,encoding,disagreement
0,858,"[Good, None, None, None, Minimal, None]","[1, 1, 0, 1, 0]",True
0,710,"[Basic, None, None, None, Minimal, None]","[1, 1, 1, 0, 0]",True
0,692,"[None, Basic, None, None, None, Minimal]","[1, 1, 1, 0, 0]",True
0,604,"[Excellent, Good, Basic, Basic, Basic]","[0, 0, 1, 1, 1]",True
0,523,"[None, Basic, None, None, None]","[1, 0, 1, 0, 0]",True
0,857,"[Minimal, Excellent, None, Minimal, Minimal]","[1, 1, 0, 0, 1]",True
0,650,"[Good, Basic, Minimal, Minimal, Minimal, Basic]","[0, 1, 1, 1, 0]",True
0,399,"[Basic, Minimal, None, Basic, Minimal]","[1, 1, 1, 0, 0]",True
0,925,"[Excellent, Basic, Good, Minimal, None, Minimal]","[1, 1, 1, 1, 1]",True
0,79,"[None, Minimal, Basic, Minimal, Minimal, None]","[1, 1, 1, 0, 0]",True
0,524,"[Minimal, Basic, None, Minimal, Minimal]","[1, 1, 1, 0, 0]",True

In [12]:
df[df["Unnamed: 0"] == 858]

,Unnamed: 0,id,text,educational_value_labels,annotator_ids,problematic_content_label_present,problematic_content_label_agreement,language_names,language_code,encoding,disagreement
858,858,9e84d3c6-1b70-4aef-909d-95026340a8bf,Den 3.7. skrev jeg om Abbey Road og også den n...,"['None', 'Minimal', 'None']",['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False

In [25]:
aleks_df = hd_df.head(50).copy()
william_df = hd_df.tail(51).copy()
len(aleks_df), len(william_df)

(50, 51)

In [13]:
new_aleks = pd.DataFrame()

In [39]:
indx = 11
df_in_question = hd_annotated_combined

fw_indx = int(df_in_question.iloc[indx]["id"])
print("INDEX:", fw_indx)
fwc_row = df[df["Unnamed: 0"] == fw_indx]
display(fwc_row["educational_value_labels"])
fwc_row["text"].values[0]

IndexError: single positional indexer is out-of-bounds

In [ ]:
indx = 4
display(aleks_df.iloc[indx]["educational_value_labels"])
aleks_df.iloc[indx]["text"]

IndexError: single positional indexer is out-of-bounds

In [38]:
label_index = 2

labels = ["None", "Minimal", "Basic", "Good", "Excellent"]
# display(df_in_question.iloc[indx]["education_value_labels"])

new_aleks = pd.concat([new_aleks, fwc_row], ignore_index=False)
loc_n = new_aleks.index[indx]
display(loc_n)
new_aleks.loc[loc_n, "educational_value_labels"] = [labels[label_index]]

524

In [16]:
new_aleks.iloc[indx]["educational_value_labels"]

['None']

In [40]:
new_aleks

,Unnamed: 0,id,text,educational_value_labels,annotator_ids,problematic_content_label_present,problematic_content_label_agreement,language_names,language_code,encoding,disagreement
858,858,9e84d3c6-1b70-4aef-909d-95026340a8bf,Den 3.7. skrev jeg om Abbey Road og også den n...,[None],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
710,710,ecde814d-1ac3-46c6-a851-d5f99ea8445a,#5 Nu er det så smart med Valve at de har stea...,[None],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
692,692,218a5779-efaf-45ba-b86a-cc0b73f8494d,Fullface dykkermasker\nWebshops med fullface d...,[None],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n 'b98...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
604,604,5e5e8f2b-1547-406e-a8f4-c4828a18733d,"Kirsebærtræer findes i forskellige sorter, hve...",[Excellent],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
523,523,64eb325d-1c03-4016-9435-fff6269a41ea,"Trangia Gasbrænder med gevind\n469,00 kr.\nTra...",[None],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
857,857,69c0682f-4c9c-44e0-b691-2f1fe115ba67,Medlemsmøde\n\n\nGeneralforsamling 2017\nAfhol...,[Basic],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
650,650,70bc7750-be93-4b61-babc-8958ebf4d022,Den seneste tids meget varme vejr har gjort øe...,[Basic],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
399,399,b20402d1-8250-410c-b177-966b8ba16d61,Online shopping råd\n- Levering\nMasser af e-f...,[Minimal],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
925,925,da7bd69c-5722-460f-a5bb-b2ea05175a0c,"Nogensinde ved Nemlig hvad du vil sige, men di...",[Basic],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '998...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
79,79,808f8f9e-802e-4ebe-a3da-403e418fc504,Vi er så stolte når andre passionerede madnørd...,[None],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n 'b98...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False
524,524,91460d0a-2e73-4702-9bb5-3a1727baada9,"Hvis du drikker som resten af landet, glemmes ...",[Basic],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 0, 0, 0, 0]",False

In [41]:
new_aleks.to_csv('annotations_relabled.csv', index=True)

In [450]:
pd.read_csv('annotations_relabled.csv', index_col=0)

,id,text,educational_value_labels,annotator_ids,problematic_content_label_present,problematic_content_label_agreement,language_names,language_code,encoding,disagreement,education_value_labels
9,49025c14-ad88-406c-b52d-e1362d78adfd,Hvordan laver jeg backup?Hvordan laver jeg let...,['None'],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[1, 0, 1, 0, 0]",True,NaN
11,477917cb-7d69-46e4-89cd-bc693d68a56e,1 SPOT PÅ SPILLERAGENTER Af Martin Bager & Lea...,['None'],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n 'b98...,False,1.0,dan_Latn,dan_Latn,"[1, 0, 1, 0, 0]",True,NaN
26,0d7d8cd1-3dc5-4dfc-8aa1-d7b55ae92be3,Universiteter skal tiltrække internationale in...,['None'],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[1, 1, 1, 0, 0]",True,NaN
46,a74093ec-d2e5-4c77-ad2c-48c3c7f51f4f,I vrede over nye sanktioner fra FN truer Nordk...,['Good'],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[1, 1, 1, 0, 0]",True,NaN
49,92889bcf-816e-41fe-994c-423a64e13ea3,Butiksansatte: Grove tyverier skaber utryghed ...,['None'],['a0585a5c-b72f-4c3a-a2a3-17e8e0b4ea4f'\n '85a...,False,1.0,dan_Latn,dan_Latn,"[0, 1, 1, 1, 0]",True,NaN
...,...,...,...,...,...,...,...,...,...,...,...
0,650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 1, 1, 1, 0]",True,"['Good', 'Basic', 'Minimal', 'Minimal', 'Minim..."
0,399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 1, 1, 0, 0]",True,"['Basic', 'Minimal', 'None', 'Basic', 'Minimal']"
0,925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",True,"['Excellent', 'Basic', 'Good', 'Minimal', 'Non..."
0,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 1, 1, 0, 0]",True,"['None', 'Minimal', 'Basic', 'Minimal', 'Minim..."
0,524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 1, 1, 0, 0]",True,"['Minimal', 'Basic', 'None', 'Minimal', 'Minim..."

# Process Final Fineweb-C

In [43]:
# df = pd.read_parquet("hf://datasets/data-is-better-together/fineweb-c/dan_Latn/train-00000-of-00001.parquet") # Fineweb-C
df = pd.read_csv("fineweb-c_relabled.csv")

A_csv = pd.read_csv('fineweb-c_relabled_aleks.csv', index_col=0)
W_csv = pd.read_csv('Will.csv', index_col=0)

# relabeled_df = pd.concat([A_csv, W_csv], ignore_index=False)

relabeled_df = pd.read_csv('annotations_relabled.csv', index_col=0)

In [44]:
def update_labels(Df1,Df2):
    Df1 = Df1.set_index('id')
    Df2 = Df2.set_index('id')

    Df1.update(Df2[['educational_value_labels']])

    return Df1.reset_index()

In [45]:
updated_df = update_labels(df, relabeled_df)

In [46]:
hd_samples = hd_df.sample(5, random_state=42)
display(hd_samples[['id', 'text', 'educational_value_labels']])


hd_samples_ids = hd_samples['id'].tolist()

updated_samples = updated_df[updated_df['id'].isin(hd_samples_ids)]
display(updated_samples[['id', 'text', 'educational_value_labels']])

ValueError: a must be greater than 0 unless no samples are taken

In [47]:
updated_df['educational_value_labels'] = updated_df['educational_value_labels'].apply(lambda x: list(x) if isinstance(x, np.ndarray) else x)
updated_df.to_csv('fineweb-c_relabled.csv', index=True)